### ISSUE TITLE
Sass vs LESS or both?

### ISSUE THREAD

**Issue by scottaohara** [owenversteeg/min#11]
Decided to break this out of the pull request so as not to deter from that topic.

Now, as for a potential Sass version.

You're obviously right in that it would add double work to Min. With that in mind, I completely understand why you wouldn't want to take this on, which is why I wanted to bring your attention to it, rather than just creating a pull request for it.

I personally prefer Sass to LESS. And maybe it's because of that bias, but I perceive there to be a faster growing community around Sass than LESS. Most of the big frameworks are built in Sass, and even Bootstraps has recently released an official port of it as a Sass library.

The obvious value in providing both is that Min would then be available to those that prefer one language to the other.

Min is a small enough framework that updating both, while it would be extra work, would be relatively simple. Most of the syntax is the same between the two languages, and updating would likely be no worse than having to copy and paste an update from one into the other  --- (converting this over to Sass really only took about 30 minutes and that was mostly due to adding the build customization into the Sass version, as opposed to having it be a separate build page -- which cuts down on additional build updates that are separate pages/JS in the Less version).

I would be happy to help you maintain the Sass version as part or your repo, or alternatively as a separate repo (either as the fork I've created or an actual new repo) that I would update based on your direction from the official Less branch.

I guess that's a good enough place to end this for now.  Whatever you decide is cool by me.  Again, thanks for being open to the suggestion.

**Comment by owenversteeg** [comment]
I think there are several points here:
- Is using Sass worth the extra work?
  - It might encourage more people to contribute, which is good. Also, you say you're willing to maintain the SASS version, so this point is almost moot.
- Is Sass more popular than LESS?
  - It doesn't look like it. [Google Trends](http://www.google.com/trends/explore#q=Sass%20CSS%2C%20LESS%20CSS&cmpt=q) seems to think LESS is somewhat more popular. However, popularity isn't terribly important, and anyway I see quite a number of frameworks either entirely in Sass or with a Sass version.

I think that there's a convincing enough argument for Min to be in both Sass and LESS. It looks like there are two options:
- A separate repo; you could call it min-sass and I could list it as the "official Sass repo"
- A folder in the current repo; every time there's a PR I'll just ping you and you can update the Sass.

I prefer the option of a folder in the current repo - it would be less (pardon my pun) daunting for contributors that would like to contribute in either LESS, Sass, or both to just fork one repo instead of two.

Let me know what you prefer.

**Comment by scottaohara** [comment]
I would prefer to have it just be a folder within the main repo. As you said, it'd be better for contributors, and general discoverability for everything to be under one roof than having "duplicate" repos. Plus, it's your project and as such, you should be the owner of both :)

The division of labor (you pinging me when updates occur to the Less branch) sounds just fine by me.  

As for file structure, may I recommend that it might make sense to put all files pertaining to Less in one folder, all the Sass files in another, and then have the main directory be for demo/documentation that pertains to both version. I'd be happy to further document out how the Sass files work in a readme for that particular folder, as well as document out the Sass setup process.

If you agree to this structure, I'd say the best thing would probably to be for you to organize the files the way you'd like first, and then I can pull down your changes and restructure my Sass branch accordingly.

Thanks again

**Comment by owenversteeg** [comment]
Yep, that structure sounds good. If you want to fork it and make a PR I'll merge in your changes. I'm thinking to just put the Sass files in an (all-lowercase, to fit the naming convention) folder like the LESS files are - with each section (buttons, navbar, headers, etc.) in a separate file. If you could make a README.md for the sass folder that'd be great, and I can make one in the less folder. 

I've just listed you as the Sass version maintainer in the README and gave you write access to Min; however, I'd still prefer if you could make a PR from your fork and merge it in yourself when you want to make changes (this is what other popular projects do as well, and it seems to work well.)

I suppose eventually the build script should be modified to ask whether to build Min from Sass or LESS, but that's an issue for later.

**Comment by scottaohara** [comment]
Cool.  thank you. I'll work on the readme and organize stuff and add it to the branch to merge.  I'll aim to get this done over the next day or two.
