### ISSUE TITLE
New website for Min

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#20]
Min's current website is quite outdated, and the source is kind of hideous in places. It's also slightly buggy.

The example page for Min 2.0 will be here: http://pasteht.ml/3M94h (the URL will still be minfwk.com, this is just a demo.)

This also features the new responsive navbar styling I hope to implement soon. Resize your browser window to test it out - it's entirely CSS-based, unlike Bootstrap.

Please leave feedback!

**Comment by chrisdotcode** [comment]
Hello there, I've been a huge fan of min since I saw it first on HN. JavaScript-less feature-parity with bootstrap in around a kilobyte sounds like a dream, and I'd like to start helping out :)

On to the link:

After viewing in both firefox and chrome, it doesn't seem the that navbar actually has any styling at all. And neither do the messages. They just appear as plain HTML to me.

And speaking of messages, custom tags like <message> or <ico> aren't semantic. Why not <div> and <span> with custom classes, instead?

And as for a grid system, why not go up to 12, instead of ten? Not only for feature-parity with bootstrap, but 12 divides into 3 rows _or_ 4 rows nicely when needed, as opposed to just 5 or 2, that you would get with 10.

Finally, when you minimize the site, it still spills over the edges (at least it does in the firefox mobile preview), and I think that's because of all of the <pre> tags used in the documentation.

I'm actually not a designer, but I'll be happy to submit pull requests as needed.

**Comment by scottaohara** [comment]
heya chris,

a lot of the stuff you mentioned has been addressed in the work that's being done on Min.  Check out the latest Less & Sass files in the repository.

However, you bring up a topic that I had been meaning to ask myself.  While messages aren't part of the main Min framework anymore, I also was wondering what the thought on using &lt;imessage> and &lt;ico> was, since they're not part of the HTML spec.

I've never had a problem rendering them, but it may make sense to convert those over to class names to be used on container elements of any type.

**Comment by owenversteeg** [comment]
@scottaohara Good point. I removed `<message>` elements already and I think it'd be a great idea to change `<ico>` elements to `<span class="ico">`s. Bootstrap uses `<i>` but [about 65% of people don't think this is semantically correct.](http://stackoverflow.com/questions/11135261/i-tag-for-icons)

**Comment by scottaohara** [comment]
i'll push an update to change this later today, unless you get to it first

**Comment by owenversteeg** [comment]
@chrisdotcode That's an old page - I forgot to update the link. The current latest is at http://pasteht.ml/cwQ02. As a matter of fact, 12-column grids have already been committed (issue #16) and will be used in the upcoming Min 2.0 release (as @scottaohara said.) You can also see them on the updated demo page.

Also, I'd love it if you could help out with Min! If you're looking for something to do, I'd say the best thing you could do is to help with #17 - just make comments in the format of the original post. I realize that this is a bit tedious, however, so if you want to help out with something else I think fixing issue #15 is a great start.

**Comment by owenversteeg** [comment]
I've revised the page even further, adding information about the percent of browsers supported. http://pasteht.ml/21f15

[edit] Latest page is at http://pasteht.ml/50h26

[edit edit] Latest page is at http://pasteht.ml/Rg0B0

**Comment by chrisdotcode** [comment]
Sorry about the stagnant reply, I'll check through the issues and see how I can help :)

**Comment by owenversteeg** [comment]
@chrisdotcode That'd be great, thanks! The only thing (pretty much) standing in the way of Min 2.0 is Bootstrap compatibility. Check out issue #17 and comment in the style of the original comment if you can. If you're better at JS, check out #15.

**Comment by owenversteeg** [comment]
New site was pushed with Min 2.0. Check it out!
