### ISSUE TITLE
How to add additional breakpoints?

### ISSUE THREAD

**Issue by COLABORATI** [owenversteeg/min#55]
Hi, great framework!

However, from looking at the source I am not 100% sure about what would be the best way to add one or two additional breakpoints for media queries and still keep compatibility with the grid and future updates. Would you like to explain in a few sentences what is the recommended method of adding, say at 320 and 720 pixels witdth? This would be very appreciated!

Thanks!

**Comment by scottaohara** [comment]
for any custom code, you could always create separate sass or less partial files to add to the build.

specifically for the sass, as i know that more than less, you could create a separate folder to place your grid partial files in, and then the only file from the min framework you'd have to update is the master file (just include an import to you new file there).  that way if you ever want to pull down a new version of min, the only file you'd have to concern yourself with overwriting would be the master file, because your custom partials are located in a separate folder.

**Comment by COLABORATI** [comment]
Ok, that was easy, thank you!
