### ISSUE TITLE
New button styles

### ISSUE THREAD

**Issue by owenversteeg** [owenversteeg/min#6]
Some people have criticized the current button styles, so this thread is where people can vote on button styles.

Current buttons:
![Buttons](http://i.imgur.com/HWc5MIk.png)

New button design A:
![Buttons](http://i.imgur.com/wayS7Nu.png)

New button design B:
![Buttons](http://i.imgur.com/vkS9cD6.png)

New button design C:
![Buttons](http://i.imgur.com/gnQiNLc.png)

Please vote (with comments) for which button design you like.

**Comment by sleepdeprecation** [comment]
Why have the rounded corners? Why not just get rid of the shadow? The shadow's the only thing that looks funky to me.

**Comment by owenversteeg** [comment]
Hmm. I've added an option (C) which is the buttons with no rounded corners and no shadow.

That said, I don't think that the square buttons show affordance. To each their own, I suppose.

**Comment by scottaohara** [comment]
changing my vote to C.

**Comment by nsanden** [comment]
Definitely B

**Comment by owenversteeg** [comment]
I vote A

**Comment by rofrol** [comment]
B

**Comment by enkrates** [comment]
I prefer B.

**Comment by hliyan** [comment]
B

**Comment by alfg** [comment]
C. Seems the most minimal.

**Comment by mcallan83** [comment]
B

**Comment by jboverfelt** [comment]
B

**Comment by ghost** [comment]
C

**Comment by ghost** [comment]
C

**Comment by owenversteeg** [comment]
Thanks everyone for voting! In preparation for the launch of Min 2, I'm closing this issue. Here's the vote breakdown:

![Votes](http://i.imgur.com/eReSrB9.png?1)

# A (1)
- @owenversteeg

# B (6)
- @nsanden 
- @rofrol 
- @enkrates 
- @hliyan 
- @mcallan83 
- @jboverfelt 

# C (5)
- @dkuntz2 
- @scottaohara 
- @alfg 
- @iamguiller 
- @ramirovjr 

If you prefer another button choice, feel free to say so. Remember, there's always another opportunity to change the button look & feel for Min 3! If you have another button style idea, just comment with an image.

**Comment by owenversteeg** [comment]
hey @scottaohara could you check over my edit to [/sass/_button.scss](https://github.com/OwenVersteeg/min/blob/gh-pages/sass/_button.scss)? I think my LESS background shows when I push to the sass folder. (also, I killed some whitespace - not sure if you had that there for a reason.)

**Comment by scottaohara** [comment]
I just submitted a pull request for some updates to the sass branch.

There are a few things I've done in the button.scss that you should probably look at and see if you agree (mostly adding a display: inline-block; to the button, .btn selector).

I'm guessing the white space you were referring to was the extra line breaks between rulesets?  I do that just to make things a bit easier to read.  Since extra spacing gets removed when compiling to the css / minified css, I'd like to keep it in there.

Also take note of the example I posted as http://scottohara.me/min, as it is directly related to why an inline-block should be applied to the button, .btn selector.

thanks

**Comment by enkrates** [comment]
Please correct me if I'm wrong, but it seems to me that option (B) won the vote. In any case, thanks for all the work on this great little CSS framework!

**Comment by owenversteeg** [comment]
@enkrates You're correct, thanks! I've updated the CSS and the chart accordingly.
